
server:
  port: 7777
#  ssl:
#    key-store-type: PKCS12
#    key-store: file:/home/ec2-user/keystore.p12
#    key-store-password: eddi@123
#    key-alias: tomcat

#  elasticsearch:
#    host: localhost
#    port: 9200
#    cluster-name: elasticsearch
#    rest:
#      uris: http://localhost:9200

#  main:
#    allow-bean-definition-overriding: true
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/wmc_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: eddi
    password: eddi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect


  cache:
    type: redis

  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
    username: eddi
    password: eddi@123

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB



